{{- if eq .Values.environment "dev" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
          env:
            - name: database_url
              value: jdbc:postgresql://{{ .Values.datasource.url }}:{{ .Values.datasource.port }}/postgres
            - name: database_username
              value: {{ .Values.datasource.username }}
            - name: database_password
              value: {{ .Values.datasource.password }}
            - name: tmdb_api_key
              value: {{ .Values.tmdb.apiKey }}
            - name: tmdb_api_access_token
              value: {{ .Values.tmdb.apiAccessToken }}
            - name: recaptcha_secretkey
              value: {{ .Values.recaptcha.secretkey }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
{{- end }}