{{- if eq .Values.environment "prod" }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-config
spec:
  sslPolicy: movie-ssl-policy # https://console.cloud.google.com/net-services/ssl-policies/
  redirectToHttps:
    enabled: true
{{- end }}