{{- if eq .Values.environment "prod" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: "frontend-config"
    kubernetes.io/ingress.global-static-ip-name: "movie-project-ip" # https://console.cloud.google.com/networking/addresses/
    networking.gke.io/managed-certificates: "movie-cert" # https://console.cloud.google.com/security/ccm/
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: {{ .Values.frontend.service.port }}
{{- end }}